import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class UpdateJsonSchema {
    /**
     * Definition of json draft-04 schema
     */
    static String defaultSchema = "{\n\t\"$schema\":\"http://json-schema.org/draft-04/schema#\",";

    /**
     * Variable that contains the allOf definition to replace the anyOf generated by jsonix
     */
    static String anyOf;

    /**
     * Pattern that matches the first entry {
     */
    static String startPattern = "^\\{";

    /**
     * Pattern that matches the jsonix schema definitions
     */
    static String jsonixSchemaPattern = "(\s+)\"\\$ref\":\"http://www.jsonix.org/jsonschemas/w3c/2001/XMLSchema.jsonschema#/definitions/(.*?)\"";
    /**
     * Main method for the java class. It requires 3 input parameters
     *  - input file of the jsonix schema definition
     *  - Name of the json schema object/file
     *  The generated output file is ./generated/[SchemaObject].schema.json
     *
     *  You need to run the jsonix schema generation first
     *  java -jar jsonix-schema-compiler-full-2.3.9.jar -compact -generateJsonSchema [xsd schema] -d [output jsonix dir] -p [Json Schema object]
     * @param args Input arguments
     */
    public static void main(String[] args) throws IOException {
        String jsonInputSchemaFile = args[0];
        String jsonSchemaObject = args[1];
        String jsonOutputSchemaFile = Paths.get(jsonInputSchemaFile).getParent() + File.separator + "generated" + File.separator + jsonSchemaObject + ".schema.json";

        anyOf = "\t\"allOf\": [\n" +
                "        {\n" +
                "            \"type\": \"object\",\n" +
                "            \"required\": [\""+ jsonSchemaObject + "\"], \n" +
                "            \"properties\": {\n" +
                "                \"VisitTruck\": {\"$ref\": \"#/definitions/VisitTruck\"}\n" +
                "            }\n" +
                "        } \n" +
                "    ]\n" +
                "}";

        System.out.println("Updating " + jsonInputSchemaFile + " for " + jsonSchemaObject);
        List<String> replacedContent = handleFile(jsonInputSchemaFile);
        Files.write(Paths.get(jsonOutputSchemaFile), replacedContent);
        System.out.println("\nGenerated " + jsonOutputSchemaFile);
    }

    /**
     * Handle file method that replaces the jsonix specific definitions
     * @param inputFile full path to the jsonix input file
     * @return List of replaced lines
     */
    private static List<String>  handleFile(String inputFile) throws IOException {
        List<String> replaced = new ArrayList<>();
        try (FileInputStream inputStream = new FileInputStream(inputFile);
             Scanner sc = new Scanner(inputStream)) {
            while (sc.hasNextLine()) {
                String line = sc.nextLine();
                //add default schema
                Pattern p = Pattern.compile(startPattern);
                Matcher m = p.matcher(line);
                if (m.matches()) {
                    System.out.println("Adding entry for default schema");
                    replaced.add(defaultSchema);
                    continue;
                }

                //replace refs
                p = Pattern.compile(jsonixSchemaPattern);
                m = p.matcher(line);
                if (m.matches()) {
                    String spaces = m.group(1);
                    String type = m.group(2);
                    System.out.println("Found entry for jsonix def: " + type);
                    String newLine;
                    switch (type) {
                        case "string" -> {
                            newLine = spaces + "\"type\": \"string\"";
                            System.out.println("   Replacing with json string");
                        }
                        case "decimal" -> {
                            newLine = spaces + "\"type\": \"number\"";
                            System.out.println("   Replacing with json number");
                        }
                        case "integer" -> {
                            newLine = spaces + "\"type\": \"integer\"";
                            System.out.println("   Replacing with json integer");
                        }
                        case "dateTime" -> {
                            newLine = spaces + "\"type\": \"string\"," + "\n" + spaces + "\"format\": \"date-time\"";
                            System.out.println("   Replacing with json string and format date-time");
                        }
                        default -> {
                            newLine = spaces + "\"type\": \"YOU SHALL NOT PASS!!!\"";
                            System.out.println("   >>>>> Did not find a match for type");
                        }
                    }
                    replaced.add(newLine);
                    continue;
                }

                //replace anyOf
                p = Pattern.compile("\s+\"anyOf\".*");
                m = p.matcher(line);
                if (m.matches()) {
                    System.out.println("found entry for anyOf");
                    replaced.add(anyOf);
                    break;
                }
                replaced.add(line);
            }
            if (sc.ioException() != null) {
                throw sc.ioException();
            }
        }
        return replaced;
    }
}
